### ISSUE TITLE
run_flops_estimation.py AssertionError: Invalid input types tensor

### ISSUE THREAD

**Issue by anitaawari** [facebookresearch/mobile-vision#124]
I am getting below error in run_flops_estimation.py run. 

python3 -m examples.run_flops_estimation
Arguments ['width_divisor'] skipped for op Conv2d
Traceback (most recent call last):
  File "anaconda3/envs/meta_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "anaconda3/envs/meta_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mobile-vision/examples/run_flops_estimation.py", line 51, in <module>
    run_flops_estimation()
  File "mobile-vision/examples/run_flops_estimation.py", line 47, in run_flops_estimation
    flops_utils.print_model_flops(model, input_batch)
  File "mobile-vision/mobile_cv/lut/lib/pt/flops_utils.py", line 196, in print_model_flops
    assert isinstance(inputs, (tuple, list)), f"Invalid input types {inputs}"
AssertionError: Invalid input types tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,

Please help me to resolve it

**Comment by anitaawari** [comment]
mobile-vision/mobile_cv/lut/lib/pt/flops_utils.py", line 196, in print_model_flops
    assert isinstance(inputs, (tuple, list)), f"Invalid input types {inputs}"

**Comment by wat3rBro** [comment]
The `print_model_flops` takes list of tensors as input, for single tensor input, say the model is called as `model(x)`, the `input_batch` should be `(x,)`.
