### ISSUE TITLE
ImportError: cannot import name 'get_fbgemm_backend_config' from 'torch.ao.quantization.backend_config' (-/python3.8/site-packages/torch/ao/quantization/backend_config/__init__.py)

### ISSUE THREAD

**Issue by HenryZ94264** [facebookresearch/mobile-vision#142]
I'm running the experiment code of the [https://github.com/facebookresearch/sylph-few-shot-detection.git](Sylph), which is build on AdelaiDet, Detectron2, D2go, and this mobile-vision. But the following error happened:

Traceback (most recent call last):
  File "tools/train_net.py", line 21, in <module>
    from d2go.distributed import launch
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/__init__.py", line 15, in <module>
    initialize_all()
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/initializer.py", line 16, in initialize_all
    _initialize_all(boostrap_registries=boostrap_registries)
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/initializer.py", line 23, in _initialize_all
    _populate_registries()
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/initializer.py", line 51, in _populate_registries
    from d2go.modeling.backbone import fbnet_v2  # noqa
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/modeling/__init__.py", line 6, in <module>
    from . import backbone, meta_arch, modeldef  # noqa  # noqa  # noqa
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/modeling/meta_arch/__init__.py", line 6, in <module>
    from . import fcos, panoptic_fpn, rcnn, retinanet, semantic_seg  # noqa
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/modeling/meta_arch/rcnn.py", line 30, in <module>
    from mobile_cv.arch.utils.quantize_utils import (
  File "<frozen zipimport>", line 259, in load_module
  File "/data0/file_server/zh/exp/ifsod/env/lib/python3.8/site-packages/mobile_cv-0.1-py3.8.egg/mobile_cv/arch/utils/quantize_utils.py", line 15, in <module>
ImportError: cannot import name 'get_fbgemm_backend_config' from 'torch.ao.quantization.backend_config' (/data0/file_server/zh/exp/ifsod/env/lib/python3.8/site-packages/torch/ao/quantization/backend_config/__init__.py)

It seems this is caused by mobile cv, how can I solved this problem?

The following is my environment setting:
Pytorch=1.12+cu113
torchvision=0.13.1+cu113

**Comment by wat3rBro** [comment]
@HenryZ94264 Those functions are not available in PyTorch 1.12, please upgrade to 1.13+.
