### ISSUE TITLE
run_fbnet_v2.py example - Invalid arch name dmasking_l3

### ISSUE THREAD

**Issue by apivovarov** [facebookresearch/mobile-vision#43]
Error
```
$ python3 run_fbnet_v2.py 
Traceback (most recent call last):
  File "/Users/pivovaa/workspace/mobile-vision/mobile_cv/model_zoo/models/fbnet_v2.py", line 73, in _create_builder
    arch_def = json.loads(arch_name_or_def)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_fbnet_v2.py", line 54, in <module>
    run_fbnet_v2()
  File "run_fbnet_v2.py", line 37, in run_fbnet_v2
    model = fbnet(model_name, pretrained=True)
  File "/Users/pivovaa/workspace/mobile-vision/mobile_cv/model_zoo/models/fbnet_v2.py", line 171, in fbnet
    model = FBNet(arch_name, **kwargs)
  File "/Users/pivovaa/workspace/mobile-vision/mobile_cv/model_zoo/models/fbnet_v2.py", line 128, in __init__
    self.backbone = FBNetBackbone(
  File "/Users/pivovaa/workspace/mobile-vision/mobile_cv/model_zoo/models/fbnet_v2.py", line 112, in __init__
    builder, arch_def = _create_builder(arch_name)
  File "/Users/pivovaa/workspace/mobile-vision/mobile_cv/model_zoo/models/fbnet_v2.py", line 76, in _create_builder
    assert arch_name_or_def in modeldef.MODEL_ARCH, (
AssertionError: Invalid arch name dmasking_l3, available names: dict_keys(['default', 'default_i8f', 'eff_0', 'eff_1', 'eff_2', 'eff_3', 'eff_4', 'eff_5', 'eff_6', 'eff_7', 'eff_8', 'eff_l2', 'fbnet_a', 'fbnet_b', 'fbnet_c', 'fbnet_96', 'fbnet_a_i8f', 'fbnet_b_i8f', 'fbnet_c_i8f', 'fbnet_96_i8f', 'FBNetV2_F0', 'FBNetV2_F1', 'FBNetV2_F2', 'FBNetV2_F3', 'FBNetV2_F4', 'FBNetV2_L1', 'FBNetV2_L2', 'FBNetV2_F0_i8f', 'FBNetV2_F1_i8f', 'FBNetV2_F2_i8f', 'FBNetV2_F3_i8f', 'FBNetV2_F4_i8f', 'FBNetV2_L1_i8f', 'FBNetV2_L2_i8f', 'FBNetV3_A', 'FBNetV3_B', 'FBNetV3_C', 'FBNetV3_D', 'FBNetV3_E', 'FBNetV3_F', 'FBNetV3_G', 'FBNetV3_A_i8f', 'FBNetV3_B_i8f', 'FBNetV3_C_i8f', 'FBNetV3_D_i8f', 'FBNetV3_E_i8f', 'FBNetV3_F_i8f', 'FBNetV3_G_i8f', 'mnv2', 'mnv3', 'mnv3_small', 'mnv2_i8f', 'mnv3_i8f', 'mnv3_small_i8f'])
```

**Comment by newstzpz** [comment]
The models `dmasking_*` has been renamed to `FBNetV2_*`. Also please consider using our latest models FBNetV3 like `FBNetV3_D`/`FBNetV3_E`.

**Comment by apivovarov** [comment]
Probably the examples should be fixed then https://github.com/facebookresearch/mobile-vision/tree/master/examples
